# Generated by Django 5.2.8 on 2025-11-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_schoolclass_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Student's photo for profile & report cards.",
                null=True,
                upload_to="student_photos/",
            ),
        ),
    ]
