# Generated by Django 5.2.8 on 2025-11-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolclass",
            options={
                "ordering": ["school__name", "name", "section"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["school_class__name", "roll_number"]},
        ),
    ]
