# Generated by Django 5.2.8 on 2025-11-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_name", models.CharField(max_length=50)),
                ("term", models.CharField(blank=True, max_length=20, null=True)),
                ("marks_obtained", models.FloatField()),
                ("max_marks", models.FloatField()),
                ("attendance_percent", models.FloatField(default=100.0)),
                ("assignments_completed", models.IntegerField(default=0)),
                ("exam_date", models.DateField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject", "exam_name", "term")},
            },
        ),
    ]
