# Generated by Django 5.0.2 on 2025-12-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0002_alter_assessment_unique_together_assessment_topic_and_more",
        ),
        ("students", "0004_alter_schoolclass_options_alter_student_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assignments_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="attendance_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="exam_date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="exam_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="marks_obtained",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="max_marks",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="term",
            field=models.CharField(blank=True, default="1", max_length=50),
            preserve_default=False,
        ),
    ]
