# Generated by Django 5.2.8 on 2025-11-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School this user belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="schools.school",
            ),
        ),
    ]
