# Generated by Django 5.2.8 on 2025-11-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo for this user.",
                null=True,
                upload_to="user_photos/",
            ),
        ),
    ]
