# Generated by Django 5.2.8 on 2025-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacher_signature",
            field=models.ImageField(
                blank=True,
                help_text="Signature image for teachers, shown on marks cards.",
                null=True,
                upload_to="teacher_signatures/",
            ),
        ),
    ]
