# Generated by Django 5.2.8 on 2025-11-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetableentry",
            options={"ordering": ["school_class", "day_of_week", "period"]},
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="students.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={("school_class", "day_of_week", "period")},
        ),
    ]
