# Generated by Django 5.2.8 on 2025-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier per school (e.g. 'green-valley').",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True, help_text="CSS color (e.g. #2563eb).", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
    ]
